version: "3.3"
services:
  e-commerce:
    image: 'hippotas/e-commerce-1'
    ports:
     - 3100
    environment:
      - SERVICE_PORTS=3100
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      - logging-net

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.5.1'
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-vol:/usr/share/elasticsearch/data 
    networks:
      - logging-net
    environment:
      - xpack.security.enabled=false
    depends_on:
      - e-commerce

  fluentd:
    image: melvindave/fluentd-elastic:1.0
    restart: always
    ports:
      - "24224:24224"
    networks:
      - logging-net
    depends_on:  
      - elasticsearch
    volumes:
      - ./fluentd/etc:/fluentd/etc   
      - ./nginx/log:/var/log/nginx   

  kibana:
    image: 'docker.elastic.co/kibana/kibana:6.5.1'
    restart: always
    ports:
      - "5601:5601"
    networks:
      - logging-net
    depends_on:
      - fluentd    
  
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - logging-net
    deploy:
      replicas: 1  
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    logging:
      driver: fluentd  
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
    depends_on:  
      - fluentd

networks:
  logging-net:

volumes:
  elasticsearch-vol: 
