version: "3.3"
services:  
  expresscart:
    image: "node:8"
    build: .
    container_name: "expresscart"
    environment:
      SERVICE_PORTS: "8081"
      NODE_ENV: development
      NODE_PATH: /
    command: >
      sh -c "npm run testdata && npm start"
    ports:
      - "8081:8081"
    networks:
      - logging-net
    volumes:
      - ./logs:/var/expressCart/logs/ 
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo:3.4.10
    volumes:
      - expresscart-mongo-data:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
    networks:
      - logging-net
      
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.5.1'
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-vol:/usr/share/elasticsearch/data 
    networks:
      - logging-net
    # environment:
    #   - xpack.security.enabled=false
    expose:
      - 9200

  fluentd:
    image: melvindave/fluentd-elastic:1.0
    restart: always
    ports:
      - "24224:24224"
    networks:
      - logging-net
    depends_on:  
      - elasticsearch
    links:
      - elasticsearch
    volumes:
      - ./fluentd/etc:/fluentd/etc   
      - ./nginx/log:/var/log/nginx
      - ./logs:/var/expressCart/logs/

  kibana:
    image: 'docker.elastic.co/kibana/kibana:6.5.1'
    restart: always
    ports:
      - "5601:5601"
    networks:
      - logging-net
    depends_on:
      - fluentd  
    links:
      - fluentd  
  
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - logging-net
    deploy:
      replicas: 1  
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    logging:
      driver: fluentd  
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
    depends_on:  
      - fluentd
      - expresscart

networks:
  logging-net:

volumes:
  elasticsearch-vol:
  expresscart-mongo-data: